server:
  port: 8080
  context-path: /api

#userService:
#  ribbon:
#    listOfServers: http://localhost:8082, http://localhost:8001
#
#todoService:
#  ribbon:
#    listOfServers: http://localhost:8088, http://localhost:8002
zuul:
  routes:
    sensitiveHeaders:
    users:
      serviceId: user
      path: /users/**
      stripPrefix: false

    todos:
      serviceId: todo
      path: /todos/**
      stripPrefix: false

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /api/health

