spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/new_todo?createDatabaseIfNotExist=true
    username: root
    password: Zhuo19930921!

jpa:
  show-sql: true

server:
  port: 8080
